language: python
python:
  - 3.5
  - 3.6
install:
  - pip install .
  - pip install -r requirements.txt
before_script: cd test/
script:
  - pytest config_test.py
  - pytest simple_project_test.py
  - pytest -k "not isolated"
